### ISSUE TITLE
getAllClientsUUID() returns ERROR when no user is connected

### ISSUE THREAD

**Issue by jim-bcom** [SolarFramework/Sample-Relocalization#8]
**HOW TO REPRODUCE**
* Start SolAR services
* Run [reloc multi viewer](https://github.com/SolarFramework/Service-Relocalization/tree/feature/ServiceManager/SolARService_MappingAndRelocFrontend/tests/SolARServiceTest_MappingAndRelocFrontend_Multi_Viewer) when no user is connected

**EXPECTED BEHAVIOR**
* No logs, or something like "No user currently connected", "Waiting for a connected user...", ....

**OBSERVED BEHAVIOR**
* Message `Failed to get all clients UUID` is logged repeatedly

The message could be reworked on the viewer application side if returning an ERROR is indeed meaning the list is empty.

But it probably makes more sense to consider in [getAllClientsUUID()](https://github.com/SolarFramework/Sample-Relocalization/blob/feature/ServiceManager/SolARPipeline_MappingAndRelocalizationFrontend/src/SolARMappingAndRelocalizationFrontendPipeline.cpp#L326) that an empty list as a valid result, and keep the ERROR return code for actual errors (exception, insertion failure,...). 
The logged message is confusing and leads to think that something went wrong with the request whereas it reports that no user is connected which is a valid scenario.
Furthermore, nothing in the [documentation](https://github.com/SolarFramework/SolARFramework/blob/feature/ServiceManager/interfaces/api/pipeline/IAsyncRelocalizationPipeline.h#L96) seems to state that returning an empty list is an error.

**Comment by cutullic** [comment]
Issue fixed in last commit
